runtime: python37
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.80
  min_instances: 0
  max_instances: 2
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  YANDEX_TRANSLATOR_KEY: trnsl.1.1.20190906T181416Z.a31a381ea85dbbaa.1b6bb8a758d46f1cdca3afad8d71b15f5b65a4fb  

entrypoint: gunicorn -b :$PORT maskrcnn-tuuka:application -w 1 --timeout 120